#we can give info of any number of algorithm we want as per our case 
#models passed with hyperparameters inside it by refering documentation 

grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 3

model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      penalty: l2
      C: 0.1
    search_param_grid:
      penalty: 
        - l2 # Test different penalty options
      C: 
        - 0.1 # Test different regularization strengths
      solver: 
        - liblinear  # Test different solvers
      max_iter:
        - 1000

  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params: 
      n_estimators:
        - 50
    search_param_grid:
      n_estimators: 
        - 50 # Test different numbers of trees
      max_depth: 
        - 2
        - 10 # Test different maximum tree depths
      min_samples_split: 
        - 2
        - 5 # Test different minimum samples for split

  module_2:
    class: DecisionTreeClassifier
    module: sklearn.tree
    params:
      random_state: 0 
    search_param_grid:
      criterion: 
        - gini
        - entropy
      max_depth:
        - 7
        - 10
      min_samples_split:
        - 2
        - 5
      max_features:
        - 9
        - 7

  module_3:
    class: SVC
    module: sklearn.svm
    params:
      random_state: 0
    search_param_grid:
      kernel: 
        - linear
        - rbf 
      C:
        - 0.1
        - 1.0
        - 3
      gamma:
        - scale
        - auto
