#we can give info of any number of algorithm we want as per our case 
#models passed with hyperparameters inside it by refering documentation 
grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 3
model_selection:
  module_0:
    class: LogisticRegression
    module: sklearn.linear_model
    params:
      penalty: l2
      C: 0.1
    search_param_grid:
      penalty: 
      # - l1
      - l2 # Test different penalty options
      C: 
      - 0.1
      # - 1.0
      # - 10.0  # Test different regularization strengths
      solver: 
      - liblinear  # Test different solvers
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params: 
      n_estimators:
      - 50
    search_param_grid:
      n_estimators: 
      - 50
      # - 100
      # - 200  # Test different numbers of trees
      max_depth: 
      - 2
      # - 5
      # - 10  # Test different maximum tree depths
      min_samples_split: 
      - 2
      # - 5
      # - 10  # Test different minimum samples for split
